### ISSUE TITLE
TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by bradydowling** [wdavidw/node-csv-parse#115]
I get the following error when running the example for streaming a file into the parser:
```
TypeError: dest.on is not a function
```

Using this example:
```
var parse = require('node-csv-parse');
var fs = require('fs');

var parser = parse({delimiter: ';'}, function(err, data){
    if (err) return console.log("Error on parse");
    console.log(data);
});

fs.createReadStream(__dirname+'/fs_read.csv').pipe(parser);
```

**Comment by wdavidw** [comment]
I have no error here with node.js 7.2.0 and 6.7.0

**Comment by fcrick** [comment]
```
fcrick:test-csv-parse fcrick$ cat ./index.js
var parse = require('node-csv-parse');
var fs = require('fs');

var parser = parse({delimiter: ';'}, function(err, data){
    if (err) return console.log("Error on parse");
    console.log(data);
});

fs.createReadStream(__dirname+'/fs_read.csv').pipe(parser);
fcrick:test-csv-parse fcrick$ node --version
v7.3.0
fcrick:test-csv-parse fcrick$ node ./index.js
_stream_readable.js:501
  dest.on('unpipe', onunpipe);
       ^

TypeError: dest.on is not a function
    at ReadStream.Readable.pipe (_stream_readable.js:501:8)
    at Object.<anonymous> (/Users/fcrick/src/test-csv-parse/index.js:9:47)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

using node-csv-parse 1.2

**Comment by wdavidw** [comment]
The name of this module isnt "node-csv-parse" but ["csv-parse"](https://github.com/wdavidw/node-csv-parse/blob/master/package.json)

**Comment by wdavidw** [comment]
This naming scheme is the most common. you prefix in github to inform coming user this is a node related repository but you of course dont in node.js and npm because you know it is node related. The question is why in hell someone whould create "node-csv-parse" when "csv-parse" existed for years!
