### ISSUE TITLE
Error on delimiter within comment line

### ISSUE THREAD

**Issue by rogierschouten** [wdavidw/node-csv-parse#32]
The following example shows how a CSV file with a double-quote within a comment line is not parsed correctly.  Removing the comment lines solves the error.

```javascript
var fs = require("fs");
var path = require("path");
var parse = require("csv-parse");
var util = require("util");

// write a file
var testFile = path.join(__dirname, "testdata.csv");
var csv =  "Region,Site,Rack,Name,IP\n" +
"\"Alaska\",\"Site1\",\"Rack1\",\"RTU-1\",\"192.168.1.3\"\n" +
"\"Alaska\",\"Site1\",\"Rack1\",\"RTU-2\",\"192.168.1.4\"\n" +
"\"Alaska\",\"Site1\",\"Rack1\",\"RTU-3\",\"192.168.1.5\"\n" +
"\"Alaska\",\"Site1\",\"Rack1\",\"RTU-4\",\"192.168.1.6\"\n" +
"\"Alaska\",\"Site1\",\"Rack1\",\"RTU-5\",\"192.168.1.7\"\n" +
"# Comment lines start with a hash sign.\n" +
"# Use a comma to separate fields.\n" +
"# Always use double-quotes to delimit fields.\n" +
"# Empty lines are ignored.\n" +
"# If you want to use a double-quote within a field, use two. E.g. \"Some \"\"special\"\" site\"  (==> Some \"special\" site)\n";
fs.writeFileSync(testFile, csv, "utf8");

// read it again
var input = fs.createReadStream(testFile, "utf8");
var parser = parse({
	auto_parse: false, // don't convert to native datatypes
	columns: null, // return arrays not objects
	comment: "#",
	delimiter: ",",
	escape: "\"",
	quote: "\"",
	rowDelimiter: "\n",
	skip_empty_lines: true,
	trim: true
});
var output = input.pipe(parser);
output.on('error', function(error){
	throw error;
});

output.on('readable', function(){
});
```

**Comment by rogierschouten** [comment]
By the way, the error is:
```shell
Error: Invalid closing quote at line 7; found " " instead of delimiter ","
    at Parser.__write (c:\Source\eXLent_master\exlent\node_modules\csv-parse\lib\index.js:250:17)
    at Parser._transform (c:\Source\eXLent_master\exlent\node_modules\csv-parse\lib\index.js:138:10)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at ReadStream.pipeOnReadable (_stream_readable.js:643:5)
```

**Comment by wdavidw** [comment]
fixed, thanks for taking the time to stop by

**Comment by rogierschouten** [comment]
Thank you!

**Comment by rogierschouten** [comment]
Could you maybe push the new version to NPM?

**Comment by wdavidw** [comment]
done (i was doing everything from mobile which is quite amazing but not npm easy)
