### ISSUE TITLE
Line reported with inconsistent column number error is off-by-one

### ISSUE THREAD

**Issue by jacksonrayhamilton** [wdavidw/node-csv-parse#97]
Using version `1.1.0` of this library, with following code, I get an unexpected error:

```
> require('csv-parse/lib/sync')('1,2,3\na,b')
Error: Number of columns is inconsistent on line 3
    at Error (native)
    at Parser.__push (node_modules/csv-parse/lib/index.js:208:26)
    at Parser._flush (node_modules/csv-parse/lib/index.js:183:12)
    at module.exports (node_modules/csv-parse/lib/sync.js:30:10)
    at repl:1:30
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
```

The CSV was:

```csv
1,2,3
a,b
```

Since there are only two columns on line 2 of the CSV, I expect the error to be "Number of columns is inconsistent on line **2**," rather than "Number of columns is inconsistent on line **3**."

**Comment by jacksonrayhamilton** [comment]
Thanks for fixing this! Are you willing to do a release with this change?

**Comment by wdavidw** [comment]
I wasnt but since you asked for it, version 1.1.1 was just published

**Comment by ilaipi** [comment]
@wdavidw hello  I use `npm install csv` lib which dependency  `csv-parse` with the latest 1.1.7,
but this issue still exists.

**Comment by wdavidw** [comment]
then please provide a small example or testcase illustrating your issue
